name: Bot Literatur Islam

on:
  schedule:
    - cron: '0 22 * * *'
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt

      - run: python bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
